version: "3.6"

networks:
    test_network:
        name: test_network

services:
    pull_request_action:
        build:
            context: ../hyperledger-updates
            dockerfile: Dockerfile
        container_name: pull_request_action
        environment:
            - GITHUB_TOKEN=${GITHUB_TOKEN}
            - CONFIG_FILE=/actions/pull_prs.yaml
            - PR_TEMPLATE_FILE=/assets/html/template/pr-template.html
            - RELEASE_TEMPLATE_FILE=/assets/html/template/release-template.html
            - ISSUE_TEMPLATE_FILE=/assets/html/template/issue-template.html
        volumes:
            - ../actions:/actions
            - ../templates:/templates
            - ../pull-requests:/pull-requests
            - ../trending:/trending
            - ../hyperledger-updates/assets:/assets
        networks:
            - test_network

    issue_action:
        build:
            context: ../hyperledger-updates
            dockerfile: Dockerfile
        container_name: issue_action
        environment:
            - GITHUB_TOKEN=${GITHUB_TOKEN}
            - CONFIG_FILE=/actions/pull_issues.yaml
            - PR_TEMPLATE_FILE=/assets/html/template/pr-template.html
            - RELEASE_TEMPLATE_FILE=/assets/html/template/release-template.html
            - ISSUE_TEMPLATE_FILE=/assets/html/template/issue-template.html
        volumes:
            - ../actions:/actions
            - ../templates:/templates
            - ../issues:/issues
            - ../trending:/trending
            - ../hyperledger-updates/assets:/assets
        networks:
            - test_network

    release_action:
        build:
            context: ../hyperledger-updates
            dockerfile: Dockerfile
        container_name: release_action
        environment:
            - GITHUB_TOKEN=${GITHUB_TOKEN}
            - CONFIG_FILE=/actions/pull_releases.yaml
            - PR_TEMPLATE_FILE=/assets/html/template/pr-template.html
            - RELEASE_TEMPLATE_FILE=/assets/html/template/release-template.html
            - ISSUE_TEMPLATE_FILE=/assets/html/template/issue-template.html
        volumes:
            - ../actions:/actions
            - ../templates:/templates
            - ../releases:/releases
            - ../trending:/trending
            - ../hyperledger-updates/assets:/assets
        networks:
            - test_network
