version: "3.5"

services:
  jekyll:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ..:/usr/src/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: |
      bash -c "
        rm -f Gemfile.lock;
        bundle exec jekyll serve -H 0.0.0.0 -t
      "
