name: Generate PRs

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v2"
        with:
          submodules: recursive
      - name: Generate latest PR information
        run: |
          # Run the docker-compose command
          docker-compose -f docker/docker-compose.yaml up --build pull_request_action
          exit ${?}
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
      - name: Create Pull Request with new PRs
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          title: Update PRs
          labels: automerge
          signoff: true
          delete-branch: false
          commit-message: Update PRs
