name: Generate Releases

on:
  schedule:
    - cron: '0 2,8,14,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v2"
        with:
          submodules: recursive
      - name: Generate latest release information
        run: |
          # Run the docker-compose command
          docker-compose -f docker/docker-compose.yaml up --build release_action
          exit ${?}
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
      - name: Create Pull Request with new Releases
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          title: Update Releases
          labels: automerge
          signoff: true
          delete-branch: false
          commit-message: Update Releases
