name: Update Contributors

on:
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: "actions/checkout@v2"
        with:
          submodules: recursive
      - name: Get hyperledger-updates contributors information
        uses: "hyperledger-tooling/github-contributors-action@main"
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.PAT }}"
          SOURCE_GITHUB_REPOSITORY: hyperledger-tooling/hyperledger-updates
          CONTRIBUTORS_SECTION_PATTERN: "## Backend Contributors"
          CONTRIBUTORS_SECTION_END_PATTERN: "## GitHub Action Contributors"
          INPUT_TEMPLATE_FILE: ./templates/contributor-template.md
          FILE_WITH_PATTERN: ./index.md
      - name: Get action contributors information
        uses: "hyperledger-tooling/github-contributors-action@main"
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.PAT }}"
          SOURCE_GITHUB_REPOSITORY: hyperledger-tooling/github-contributors-action
          CONTRIBUTORS_SECTION_PATTERN: "## GitHub Action Contributors"
          CONTRIBUTORS_SECTION_END_PATTERN: ""
          INPUT_TEMPLATE_FILE: ./templates/contributor-template.md
          FILE_WITH_PATTERN: ./index.md
      - name: Get Hyperledger contributors information
        uses: "hyperledger-tooling/github-contributors-action@main"
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.PAT }}"
          SOURCE_GITHUB_REPOSITORY: hyperledger
          CONTRIBUTORS_SECTION_PATTERN: "## Hyperledger GitHub Contributors"
          CONTRIBUTORS_SECTION_END_PATTERN: "## Hyperledger Labs GitHub Contributors"
          INPUT_TEMPLATE_FILE: ./templates/contributor-template.md
          FILE_WITH_PATTERN: ./community.md
      - name: Get Hyperledger Labs contributors information
        uses: "hyperledger-tooling/github-contributors-action@main"
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.PAT }}"
          SOURCE_GITHUB_REPOSITORY: hyperledger-labs
          CONTRIBUTORS_SECTION_PATTERN: "## Hyperledger Labs GitHub Contributors"
          CONTRIBUTORS_SECTION_END_PATTERN: "## Hyperledger Tooling GitHub Contributors"
          INPUT_TEMPLATE_FILE: ./templates/contributor-template.md
          FILE_WITH_PATTERN: ./community.md
      - name: Get Hyperledger Tooling contributors information
        uses: "hyperledger-tooling/github-contributors-action@main"
        env:
          GITHUB_AUTH_TOKEN: "${{ secrets.PAT }}"
          SOURCE_GITHUB_REPOSITORY: hyperledger-tooling
          CONTRIBUTORS_SECTION_PATTERN: "## Hyperledger Tooling GitHub Contributors"
          CONTRIBUTORS_SECTION_END_PATTERN: "## Github Community Statistics"
          INPUT_TEMPLATE_FILE: ./templates/contributor-template.md
          FILE_WITH_PATTERN: ./community.md
      - name: Create Pull Request with new backend contributors
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          title: Update Backend Contributors
          labels: automerge
          signoff: true
          delete-branch: false
          commit-message: Update Backend Contributors
